SELECT ROUND(SUM(DISTANCE_BACK) / (10 * 1000 / 60))  AS TIME FROM

(SELECT * FROM ROUTE_BY_STOPS
JOIN STOPS
ON ROUTE_BY_STOPS.ID_STOP = STOPS.ID_STOP
WHERE ROUTE_NUMBER = 49
AND ID_DIRECTION IN (SELECT ID_DIRECTION FROM ROUTE_BY_STOPS WHERE ID_STOP = 14723)
ORDER BY ID_DIRECTION, STOP_NUMBER)

WHERE STOP_NUMBER > (SELECT STOP_NUMBER FROM ROUTE_BY_STOPS WHERE ID_STOP = 4515 AND ROUTE_NUMBER = 49)
AND STOP_NUMBER <= (SELECT STOP_NUMBER FROM ROUTE_BY_STOPS WHERE ID_STOP = 14723 AND ROUTE_NUMBER = 49)
